config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "journals#index"

  get 'journals/upload', to: 'journals#upload'
  post 'journals/bulk_create', to: 'journals#bulk_create'
  resources :journals

  resources :items
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :journals
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :item

  def self.csv_import(filename)
    require 'csv'

    open(filename, "rb:Shift_JIS:UTF-8", undef: :replace) do |f|
      CSV.new(f, {headers: true}).each do |row|

        checkin_at  = row[1]
        karte_no    = row[2] || "0000"
        person_name = row[3]
        item_name   = row[4]
        quantity    = row[5]
        unit_price  = row[6]

        unless person = Person.find_by_id(karte_no)
          person = Person.create(name: person_name, karte_no: karte_no)
        end
        unless item = Item.find_by_name(item_name)
          item = Item.create(name: item_name, price: unit_price)
        end
        person.journals.create(checkin_at: Date.strptime(checkin_at, '%Y%m%d'), item: item, quantity: quantity)
      end
    end

  end
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :journals, primary_key: :karte_no, foreign_key: :karte_no

  self.primary_key = "karte_no"
  validates :karte_no, uniqueness: true

  class << self
    def find_by_id(id)
      self.find_by_karte_no(id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price)
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload
    @journal = Journal.new
  end

  def bulk_create
    file = journal_file_params[:upload_file]
    name = file.original_filename
    salt = SecureRandom.hex(8)
    md5 = Digest::MD5.hexdigest(salt + name)

    filename = "public/upload_files/#{md5}"
    File.open(filename, 'wb') { |f|
      f.write(file.read)
    }

    Journal.csv_import(filename)
    @journal = Journal.new
    render :upload
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:checkin_at, :karte_no, :quantity, :item_id)
    end

    def journal_file_params
      params.require(:journal).permit(:upload_file)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:karte_no, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.number_field :price
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Name
      %th Price
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.price
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  %b Price:
  = @item.price

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/journals/_form.html.haml
= form_for @journal do |f|
  - if @journal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@journal.errors.count, "error")} prohibited this journal from being saved:"
      %ul
        - @journal.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :checkin_at
    = f.date_select :checkin_at
  .field
    = f.label :karte_no
    = f.number_field :karte_no
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :item
    = f.text_field :item
  .actions
    = f.submit 'Save'

app/views/journals/edit.html.haml
%h1 Editing journal

= render 'form'

= link_to 'Show', @journal
\|
= link_to 'Back', journals_path

app/views/journals/index.html.haml
%h1 Listing journals

%table
  %thead
    %tr
      %th Checkin at
      %th Karte no
      %th Quantity
      %th Item
      %th
      %th
      %th

  %tbody
    - @journals.each do |journal|
      %tr
        %td= journal.checkin_at
        %td= journal.karte_no
        %td= journal.item.name
        %td= journal.item.price
        %td= journal.quantity
        %td= journal.item.price * journal.quantity
        %td= link_to 'Show', journal
        %td= link_to 'Edit', edit_journal_path(journal)
        %td= link_to 'Destroy', journal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Journal', new_journal_path

app/views/journals/new.html.haml
%h1 New journal

= render 'form'

= link_to 'Back', journals_path

app/views/journals/show.html.haml
%p#notice= notice

%p
  %b Checkin at:
  = @journal.checkin_at
%p
  %b Karte no:
  = @journal.karte_no
%p
  %b Quantity:
  = @journal.quantity
%p
  %b Item:
  = @journal.item

= link_to 'Edit', edit_journal_path(@journal)
\|
= link_to 'Back', journals_path

app/views/journals/upload.html.haml
%h1 Upload journal

= form_for @journal, url: { action: 'bulk_create' } do |f|
  .field
    = f.file_field :upload_file
  .actions
    = f.submit "Upload"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails52</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :karte_no
    = f.number_field :karte_no
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %thead
    %tr
      %th Karte no
      %th Name
      %th
      %th
      %th

  %tbody
    - @people.each do |person|
      %tr
        %td= person.karte_no
        %td= person.name
        %td= link_to 'Show', person
        %td= link_to 'Edit', edit_person_path(person)
        %td= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b Karte no:
  = @person.karte_no
%p
  %b Name:
  = @person.name

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path